// Single source of truth for the deployed Investment contract.
// `deployment.json` is regenerated by the Hardhat deploy script
// (blockchain/scripts/deploy.js) with the real address + compiled ABI.
import deployment from "./deployment.json";

export const CONTRACT_ADDRESS = deployment.address;
export const CONTRACT_ABI = deployment.abi;
export const TARGET_CHAIN_ID = deployment.chainId;
export const MIN_INVESTMENT_WEI = deployment.minInvestmentWei;

export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

/** True once the contract has actually been deployed (non-zero address). */
export function isContractDeployed() {
  return (
    !!CONTRACT_ADDRESS &&
    CONTRACT_ADDRESS.toLowerCase() !== ZERO_ADDRESS.toLowerCase()
  );
}

// Network metadata for display + wallet_addEthereumChain.
export const NETWORKS = {
  31337: {
    chainId: "0x7a69",
    chainName: "Hardhat Local",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["http://127.0.0.1:8545"],
    blockExplorerUrls: [],
  },
  11155111: {
    chainId: "0xaa36a7",
    chainName: "Sepolia",
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.sepolia.org"],
    blockExplorerUrls: ["https://sepolia.etherscan.io"],
  },
};

/** Block-explorer URL for a tx hash, or null if the network has no explorer. */
export function explorerTxUrl(chainId, txHash) {
  const base = NETWORKS[chainId]?.blockExplorerUrls?.[0];
  return base ? `${base}/tx/${txHash}` : null;
}

/** Truncate an address for display: 0x1234…abcd */
export function shortAddress(addr) {
  return addr ? `${addr.slice(0, 6)}…${addr.slice(-4)}` : "";
}
